### PR TITLE
Fix missing const declaration.

### LINKED ISSUE #729: Build failure on Fedora
Hi friends. Not sure why I can't build this. The output is long and I'm not sure what's relevant, so [here's a pastebin](https://pastebin.com/9QYedCm7).

I believe I have all the correct dependencies:

```c
❯ meson setup --reconfigure --buildtype=release ./build
The Meson build system
Version: 1.0.1
Source dir: /home/alex/Downloads/desmume-0.9.13/desmume/src/frontend/posix
Build dir: /home/alex/Downloads/desmume-0.9.13/desmume/src/frontend/posix/build
Build type: native build
Project name: desmume
Project version: 2.7.10
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)")
C linker for the host machine: cc ld.bfd 2.39-9
C++ compiler for the host machine: c++ (gcc 13.2.1 "c++ (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)")
C++ linker for the host machine: c++ ld.bfd 2.39-9
Host machine cpu family: x86_64
Host machine cpu: x86_64
Dependency glib-2.0 found: YES 2.76.5 (cached)
Dependency sdl2 found: YES 2.26.3 (cached)
Dependency pcap found: YES 1.10.3 (cached)
Dependency zlib found: YES 1.2.13 (cached)
Dependency threads found: YES unknown (cached)
Dependency gl found: YES 1.2 (cached)
Dependency openal found: YES 1.23.0 (cached)
Dependency alsa found: YES 1.2.10 (cached)
Dependency soundtouch found: YES 2.3.1 (cached)
Dependency libagg found: YES 2.5.0 (cached)
meson.build:227: WARNING: Module SIMD has no backwards or forwards compatibility and might not exist in future releases.
Compiler supports sse2: YES
Dependency x11 found: YES 1.8.6 (cached)
Dependency gtk+-3.0 found: YES 3.24.38 (cached)
Dependency x11 found: YES 1.8.6 (cached)
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Build targets in project: 6

desmume 2.7.10

  User defined options
    buildtype: release

Found ninja-1.11.1 at /usr/bin/ninja
```

Attempting on Fedora 38, happy to provide any additional information that could help troubleshoot.

### PR DESCRIPTION
**Pull request by alexfornuto**
I discovered this bug while trying to resolve https://github.com/TASEmulators/desmume/issues/729.

### CODE REVIEW

**Comment by jkingan** [comment]
Hi @alexfornuto - Looking at your original pastebin, it appears that the version of agg being used there is not the same as this one. The error shown referencing a const m_profile isn't present in this repo. const was removed in commit [0183a2a](https://github.com/ghaerr/agg-2.6/commit/0183a2a74fb1cd06604c208947dcfa79cb636325) some time ago.

Can you verify this by looking at the very bottom of the agg_renderer_outline_aa.h file in your distribution - is there a const modifier on m_profile there?

**Comment by alexfornuto** [comment]
Hi @jkingan I haven't forgotten about this, and will look as instructed the next time I'm on the system in question.

**Comment by alexfornuto** [comment]
@jkingan Do you mean this?

```
    private:
        base_ren_type*         m_ren;
        const line_profile_aa* m_profile;
        color_type             m_color;
        rect_i                 m_clip_box;
        bool                   m_clipping;
    };
```

**Comment by jkingan** [comment]
Yes - that const is missing from the m_profile in this repo. It looks like the version you have is based on the (apparently?) now-defunct 2.5 version. If I understand the project history, this repo was forked from the original 2.4. Both this version and the 2.4 lineage have undergone development since and 2.5 kind of got orphaned (at least as I understand it.)

All that to say, the removal of the const in this repo (along with a pile of other changes in the same commit) means I don't think this version suffers from the same compilation error you received.

**Comment by alexfornuto** [comment]
@jkingan understood, thanks!

For context, I was just trying to build a hand-held game console emulator from its source when I found this issue (before realizing it was already in my distro's repos). I was trying to be a good OSS citizen and report it, but don't have the wherewithal (or interest to learn) for Fedora's bug report ecosystem. So, finding this repo, I took a stab at trying to be helpful.

If it's not the right place, then that's that. Sorry to waste your time.

**Pull request closed without merging**
